id: P1114E177
initial_creation_type: ocr
source_metadata:
  volumes:
    491d33f32de44ddeaf39e29d6609de72:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: བྱང་ཆུབ་ཀྱི་སེམས་བདེ་བའི་མན་ངག།
      total_pages: 1856
      volume_number: 14
